language: node_js
node_js:
  - 8
# - lts/* # once we support on-the-fly transpilation
install:
  - git clone https://github.com/qooxdoo/qooxdoo.git
  - git clone https://github.com/qooxdoo/qooxdoo-compiler && cd qooxdoo-compiler && npm install && cd ..
  - npm install
  - npm link
  - npm link qooxdoo-compiler/
  - chmod a+x test/test.linux.sh
script:
  - echo "Simple testing of CLI ..."
  - npm test

